# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('idaluno', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('contato', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('idatividade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('iddisciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('iddocumento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('idprofessor', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reposicoes',
            fields=[
                ('idreposicao', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('justificativa', models.CharField(max_length=300)),
                ('arquivo', models.FileField(upload_to='seacpar/%Y/%m/')),
                ('idatividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seacpar.Atividades')),
                ('iddocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seacpar.Documentos')),
                ('idprofessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seacpar.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Requerimentos',
            fields=[
                ('idrequerimento', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now=True)),
                ('posicao', models.CharField(blank=True, max_length=300)),
                ('status', models.IntegerField()),
                ('idaluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seacpar.Aluno')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seacpar.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('idturma', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='reposicoes',
            name='idrequerimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seacpar.Requerimentos'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='idcurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seacpar.Curso'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='idturma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seacpar.Turmas'),
        ),
    ]
