# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seacpar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reposicoes',
            name='idrequerimento',
        ),
        migrations.AddField(
            model_name='requerimentos',
            name='reposicoes',
            field=models.ManyToManyField(blank=True, to='seacpar.Reposicoes'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='idcurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seacpar.Curso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='idturma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seacpar.Turmas'),
        ),
        migrations.AlterField(
            model_name='reposicoes',
            name='idatividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seacpar.Atividades'),
        ),
        migrations.AlterField(
            model_name='reposicoes',
            name='iddocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seacpar.Documentos'),
        ),
        migrations.AlterField(
            model_name='reposicoes',
            name='idprofessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seacpar.Professor'),
        ),
        migrations.AlterField(
            model_name='requerimentos',
            name='idaluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seacpar.Aluno'),
        ),
        migrations.AlterField(
            model_name='requerimentos',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seacpar.Professor'),
        ),
    ]
