# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seacpar', '0002_auto_20161214_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requerimentos',
            name='reposicoes',
        ),
        migrations.AddField(
            model_name='reposicoes',
            name='idrequerimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='seacpar.Requerimentos'),
            preserve_default=False,
        ),
    ]
